# Generated by Django 5.1.1 on 2024-10-17 19:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_feedback_fid'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='real',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='fid',
            field=models.UUIDField(default=uuid.UUID('ebe62b84-f78e-4e50-a90a-71db60ee90b0'), editable=False, unique=True),
        ),
    ]
