# Generated by Django 5.1.1 on 2024-10-17 19:36

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_feedback_real_alter_feedback_fid'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='created_date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2024, 10, 18, 1, 6, 23, 711942)),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='fid',
            field=models.UUIDField(default=uuid.UUID('faa8c7c2-e8e1-49fb-a54a-2ba202107808'), editable=False, unique=True),
        ),
    ]
