# Generated by Django 5.1.1 on 2024-10-17 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_feedback_created_date_alter_feedback_fid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
