# Generated by Django 5.1.1 on 2024-10-17 19:47

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_delete_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True, default=datetime.datetime(2024, 10, 18, 1, 17, 31, 456273))),
                ('text', models.TextField(default='')),
                ('like', models.BooleanField(default=False)),
                ('comment', models.TextField(default='')),
                ('fid', models.UUIDField(default=uuid.UUID('9ceaec21-e943-4528-a47b-e3b0b49890ee'), editable=False, unique=True)),
                ('real', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
