# Generated by Django 5.1.4 on 2024-12-11 21:59

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='created_date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2024, 12, 12, 3, 29, 35, 442362)),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='fid',
            field=models.UUIDField(default=uuid.UUID('0719f8c7-bd93-4983-838b-f05f2e9451bc'), editable=False, unique=True),
        ),
    ]
