# Generated by Django 5.1.4 on 2024-12-11 22:52

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_feedback_created_date_alter_feedback_fid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='created_date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2024, 12, 12, 4, 22, 8, 542481)),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='fid',
            field=models.UUIDField(default=uuid.UUID('d8e1df23-693a-4a98-a536-c05621ad108b'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='/static/images\\user.png', null=True, upload_to='profile_images/'),
        ),
    ]
