# Generated by Django 5.1.4 on 2024-12-11 22:56

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_feedback_created_date_alter_feedback_fid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='created_date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2024, 12, 12, 4, 26, 48, 267621)),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='fid',
            field=models.UUIDField(default=uuid.UUID('a7730b24-55c4-4630-8299-b7df8b3c11fc'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='D:\\A123\\Python 3.6\\Python Projects\\Fake news Detection\\FakeNewsDetection\\mainserver\\static\\images\\user.png', null=True, upload_to='profile_images/'),
        ),
    ]
