# Generated by Django 5.1.4 on 2024-12-11 23:02

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_feedback_created_date_alter_feedback_fid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='created_date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2024, 12, 12, 4, 32, 24, 879917)),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='fid',
            field=models.UUIDField(default=uuid.UUID('27761c03-3735-4be1-9bdf-b4bf37e3ec83'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='./static/images/user.png', null=True, upload_to='profile_images/'),
        ),
    ]
