# Generated by Django 5.1.4 on 2024-12-16 11:17

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_feedback_created_date_alter_feedback_fid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='like',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='text',
        ),
        migrations.AddField(
            model_name='feedback',
            name='content',
            field=models.TextField(default='', help_text='Specify the associated content (e.g., product or post).'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - Poor'), (2, '2 - Fair'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Excellent')], default=3),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='fid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='./profile_images/user.png', null=True, upload_to='profile_images/'),
        ),
    ]
