# Generated by Django 5.1.4 on 2024-12-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_feedback_comment_remove_feedback_like_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='content',
            field=models.TextField(blank=True, default='', help_text='Specify the associated content (e.g., product or post).'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='real',
            field=models.BooleanField(default=False),
        ),
    ]
