# Generated by Django 5.1.4 on 2024-12-19 21:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_feedback_content_alter_feedback_real'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=150)),
                ('subject', models.CharField(choices=[('General Customer Service', 'General Customer'), ('Suggestions', 'Suggestions'), ('Product Suppport', 'Product Support')], max_length=30)),
                ('message', models.TextField(blank=True, default='', help_text='Specify the associated content (e.g., product or post).')),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
