# Generated by Django 5.1.4 on 2024-12-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_contactservices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactservices',
            name='message',
            field=models.TextField(blank=True, default='', help_text='Mention your resion to contact us'),
        ),
    ]
